resources:
- name: maven-examples
  type: git
  source:
   uri: https://github.com/mkyong/maven-examples.git
jobs:
- name: build-run-job
plan:
- get: maven-examples
- task: build
  config:
    plateform: linux
    image_resource:
      type: docker-image
      source:
        repository: maven
        tag: 3.6.3-jdk-11
  inputs: 
  - name: maven-examples
  outputs:
  - name: build-out
  params:
   branch: master
  run:
   path: bash
   args:
   - -exec
   -
     cd maven-examples/maven-unit-test/
     mvn clean install
  
